id: P75882287
initial_creation_type: input
source_metadata:
  title: Wealth and Prosperity Series
  language: es
  description: 'A selection of texts on the theme of wealth and prosperity including
    rites for summoning the spirit of prosperity or abundance (g.yang ''gugs):'
  volume:
    9b1ee33056af4a86902cf7770bb7566d:
      title: Sang Offering to Yellow Jambhala
      parent: Offering
    97ef624b15504aad9e1cb95e84af4f64:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Offering
    983407fec0ff4b3aa672fe592e4c6492:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Summoning Prosperity
    0aaf0b3a793040f184777f1ca0f59c84:
      title: 'The Summoning Hook of Wish-Fulfilment: An Appeal for Prosperity'
      parent: Summoning Prosperity
    52e6d2c9c6c44cbf81085bedc7f63c8a:
      title: Summoning Prosperity
      parent: Summoning Prosperity
    8f4c0ab205f24a45aab29448fbff28f3:
      title: A Brief Prayer for Summoning Prosperity
      parent: Summoning Prosperity
    a693f825132e4fa4901ee9cc572d217f:
      title: Summoning the Spirit of Abundance - The Hook of Divine Substance
      parent: Summoning Prosperity
    41e820870c694fd28515910bdd5b9284:
      title: An Appeal for the Prosperity of Teaching and Studying the Five Major
        Scriptures
      parent: Summoning Prosperity
created_at: '2022-03-01T06:34:53.425524'
last_modified_at: '2022-03-01T06:34:53.425526'
